title: ilikeshinythings Spoken Word
description:
  Click on the links to access the spoken word poetry.
  <br>
  -----
  <br>
  Data
  <br>
  <a href="https://ilikeshinythings-spokenword.github.io/facebookads">Facebook ads</a> ğŸ§  |
  <a href="https://ilikeshinythings-spokenword.github.io/iknowyoubetterthanyouknowyourself">I know you better than you know yourself</a> ğŸ’©ğŸ§  |
  <a href="https://ilikeshinythings-spokenword.github.io/whodoyouthinkyouare">Who do you think you are?</a>
  <br><br>
  Woman
  <br>
  <a href="https://ilikeshinythings-spokenword.github.io/shutthefuckup">Shut the fuck up</a> ğŸ–• |
  <a href="https://ilikeshinythings-spokenword.github.io/why">Why</a> â‰ï¸ |
  <a href="https://ilikeshinythings-spokenword.github.io/unspokencurfew">Unspoken curfew</a>
  <br><br>
  Identity
  <br>
  <a href="https://ilikeshinythings-spokenword.github.io/colour">Colour</a> |
  <a href="https://ilikeshinythings-spokenword.github.io/whodoyouthinkyouare">â€œOtherâ€ and Another â€œOtherâ€</a>
  <br><br>
  Self love
  <br>
  <a href="https://ilikeshinythings-spokenword.github.io/forgettingmyself">Forgetting myself</a> ğŸ’© |
  <a href="https://ilikeshinythings-spokenword.github.io/formybestfriend">For my best friend</a> ğŸ’©ğŸ–•ğŸ¿ |
  <a href="https://ilikeshinythings-spokenword.github.io/haveatry">Have a try</a> ğŸ’© |
  <a href="https://ilikeshinythings-spokenword.github.io/ilovemetoo">(I) love me too</a> ğŸ§  |
  <a href="https://ilikeshinythings-spokenword.github.io/upsidedownonthesofa">Upside down on the sofa</a> |
  <a href="https://ilikeshinythings-spokenword.github.io/wellmeaninglistener">Well-meaning listener</a>
  <br><br>
  Love
  <br>
  <a href="https://ilikeshinythings-spokenword.github.io/butttobutt">Butt to butt</a> |
  <a href="https://ilikeshinythings-spokenword.github.io/forgetfulllover">Forget full lover</a> |
  <a href="https://ilikeshinythings-spokenword.github.io/calm">Calm</a> |
  <a href="https://ilikeshinythings-spokenword.github.io/missyou">Miss you</a>
  <br>-----<br>
  <a href="https://ilikeshinythings-spokenword.github.io/">Back to Homepage</a>
show_downloads: false
theme: jekyll-theme-minimal
