title: ilikeshinythings Spoken Word
description:
  Click on the links to access the spoken word poetry.
  <br>
  -----
  <br>
  Data
  <br>
  <a href="https://ilikeshinythings.github.io/facebookads">Facebook ads</a> ğŸ§ 
  <br>
  <a href="https://ilikeshinythings.github.io/iknowyoubetterthanyouknowyourself">I know you better than you know yourself</a> ğŸ’©ğŸ§ 
  <br>
  <a href="https://ilikeshinythings.github.io/whodoyouthinkyouare">Who do you think you are? / â€œOtherâ€ and Another â€œOtherâ€</a>
  <br><br>
  Woman
  <br>
  <a href="https://ilikeshinythings.github.io/shutthefuckup">Shut the fuck up</a> ğŸ–•ğŸ¿
  <br>
  <a href="https://ilikeshinythings.github.io/unspokencurfew">Unspoken curfew</a>
  <br>
  <a href="https://ilikeshinythings.github.io/why">Why</a> â‰ï¸
  <br><br>
  Identity
  <br>
  <a href="https://ilikeshinythings.github.io/colour">Colour</a>
  <br>
  <a href="https://ilikeshinythings.github.io/whodoyouthinkyouare">Who do you think you are? / â€œOtherâ€ and Another â€œOtherâ€</a>
  <br><br>
  Self love
  <br>
  <a href="https://ilikeshinythings.github.io/forgettingmyself">Forgetting myself</a> ğŸ’©
  <br>
  <a href="https://ilikeshinythings.github.io/formybestfriend">For my best friend</a> ğŸ’©ğŸ–•ğŸ¿
  <br>
  <a href="https://ilikeshinythings.github.io/haveatry">Have a try</a> ğŸ’©
  <br>
  <a href="https://ilikeshinythings.github.io/ilovemetoo">(I) love me too</a> ğŸ§ 
  <br>
  <a href="https://ilikeshinythings.github.io/upsidedownonthesofa">Upside down on the sofa</a>
  <br>
  <a href="https://ilikeshinythings.github.io/wellmeaninglistener">Well-meaning listener</a>
  <br><br>
  Love
  <br>
  <a href="https://ilikeshinythings.github.io/butttobutt">Butt to butt</a>
  <br>
  <a href="https://ilikeshinythings.github.io/calm">Calm</a>
  <br>
  <a href="https://ilikeshinythings.github.io/forgetfulllover">Forget full lover</a>
  <br>
  <a href="https://ilikeshinythings.github.io/missyou">Miss you</a>
  <br>-----<br>
  <a href="https://ilikeshinythings.github.io/">Back to Homepage</a>
show_downloads: false
theme: jekyll-theme-minimal
